"""seed data

Revision ID: bcea4debee11
Revises: da1563f92346
Create Date: 2025-10-10 00:31:13.633599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import uuid
from datetime import datetime, UTC

from app.models.user import User
from app.models.bank import Bank

from sqlalchemy.orm import Session


# revision identifiers, used by Alembic.
revision: str = 'bcea4debee11'
down_revision: Union[str, None] = 'da1563f92346'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    session = Session(bind=bind)
    
    try:
        new_bank_sme = Bank(
            name='SME Mock Bank 1',
            country='South Africa',
            interest_rate_min=3.0,
            interest_rate_max=10.0,
        )
        
        session.add(new_bank_sme)
        session.commit()
        print("ORM-based seed bank SME added successfully!")
        
        new_bank_sme = Bank(
            name='SME Mock Bank 2',
            country='South Africa',
            interest_rate_min=5.0,
            interest_rate_max=11.0,
        )
        session.add(new_bank_sme)
        session.commit()
        print("ORM-based seed bank SME added successfully!")
        
        new_bank_sme = Bank(
            name='SME Mock Bank 3',
            country='South Africa',
            interest_rate_min=7.0,
            interest_rate_max=9.0,
        )
        session.add(new_bank_sme)
        session.commit()
        print("ORM-based seed bank SME added successfully!")
            
        
        new_bank_lending = Bank(
            name='SG Mock Bank 1',
            country='Singapore',
            interest_rate_min=5.0,
            interest_rate_max=11.0,
        )
        
        session.add(new_bank_lending)
        session.commit()
        print("ORM-based seed bank Lending added successfully!")
            
        # Check if seed data already exists
        existing_bank_lending = session.query(Bank).filter(Bank.name == 'SG Mock Bank 1').first()
        
        # Create new user using the model
        new_user = User(
            name='Bank Admin',
            username='bankadmin',
            email='admin@bank.com',
            profile_image_url='https://avatar.iran.liara.run/public/47',
            google_id="MOCK_LOGIN_CODE",
            uuid=uuid.uuid4(),
            created_at=datetime.now(UTC),
            updated_at=None,
            deleted_at=None,
            is_deleted=False,
            is_superuser=False,
            bank_id=existing_bank_lending.id
        )
        
        session.add(new_user)
        session.commit()
        print("ORM-based seed user added successfully!")
            
    except Exception as e:
        session.rollback()
        print(f"Error adding seed data: {e}")
        raise
    finally:
        session.close()
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    session = Session(bind=bind)
    
    try:
        # Remove the seed user
        user_to_delete = session.query(User).filter(User.username == 'bankadmin').first()
        if user_to_delete:
            session.delete(user_to_delete)
            session.commit()
            print("ORM seed user removed successfully!")
        else:
            print("ORM seed user not found.")
    except Exception as e:
        session.rollback()
        print(f"Error removing seed data: {e}")
        raise
    finally:
        session.close()
    # ### end Alembic commands ###
