"""seed_data

Revision ID: 70b5601e92ca
Revises: 9b4a980860e4
Create Date: 2025-10-04 03:51:44.722006

"""
from typing import Sequence, Union

import uuid
from datetime import datetime, UTC

from app.models.user import User
from app.models.bank import Bank

from alembic import op
from sqlalchemy.orm import Session

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70b5601e92ca'
down_revision: Union[str, None] = '9b4a980860e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    session = Session(bind=bind)
    
    try:
        existing_bank_sme = session.query(Bank).filter(Bank.name == 'SME Mock Bank').first()
        existing_bank_lending = session.query(Bank).filter(Bank.name == 'ACME Bank').first()
        
        if not existing_bank_sme:
            new_bank_sme = Bank(
                name='SME Mock Bank',
                country='India',
                interest_rate_min=3.0,
                interest_rate_max=10.0,
            )
            
            session.add(new_bank_sme)
            session.commit()
            print("ORM-based seed bank SME added successfully!")
        else:
            print("ORM-based seed bank SME already exists, skipping insertion.")
            
        if not existing_bank_lending:
            new_bank_lending = Bank(
                name='ACME Bank',
                country='Singapore',
                interest_rate_min=5.0,
                interest_rate_max=11.0,
            )
            
            session.add(new_bank_lending)
            session.commit()
            print("ORM-based seed bank Lending added successfully!")
        else:
            print("ORM-based seed bank Lending already exists, skipping insertion.")
            
        # Check if seed data already exists
        existing_user = session.query(User).filter(User.username == 'bankadmin').first()
        
        existing_bank_lending = session.query(Bank).filter(Bank.name == 'ACME Bank').first()
        
        if not existing_user:
            # Create new user using the model
            new_user = User(
                name='Bank Admin',
                username='bankadmin',
                email='admin@bank.com',
                profile_image_url='https://avatar.iran.liara.run/public/47',
                google_id="MOCK_LOGIN_CODE",
                uuid=uuid.uuid4(),
                created_at=datetime.now(UTC),
                updated_at=None,
                deleted_at=None,
                is_deleted=False,
                is_superuser=False,
                bank_id=existing_bank_lending.id
            )
            
            session.add(new_user)
            session.commit()
            print("ORM-based seed user added successfully!")
        else:
            print("ORM seed user already exists, skipping insertion.")
            
    except Exception as e:
        session.rollback()
        print(f"Error adding seed data: {e}")
        raise
    finally:
        session.close()
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    session = Session(bind=bind)
    
    try:
        # Remove the seed user
        user_to_delete = session.query(User).filter(User.username == 'orm_test_user').first()
        if user_to_delete:
            session.delete(user_to_delete)
            session.commit()
            print("ORM seed user removed successfully!")
        else:
            print("ORM seed user not found.")
    except Exception as e:
        session.rollback()
        print(f"Error removing seed data: {e}")
        raise
    finally:
        session.close()
    # ### end Alembic commands ###
