"""add insight status

Revision ID: 3818b9629c3f
Revises: 70b5601e92ca
Create Date: 2025-10-06 11:21:04.781943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3818b9629c3f'
down_revision: Union[str, None] = '70b5601e92ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loan', sa.Column('insights_status', sa.String(length=30), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loan', 'insights_status')
    # ### end Alembic commands ###
